build:
  test-gitium:
    image: presslabs/pl-test-containers:php-$$PHP_VERSION
    pull: true
    commands:
      - bash bin/install-wp-tests.sh wordpress_test root root_pass 127.0.0.1 $$WP_VERSION true
      - composer install --no-progress
      - dockerize --wait tcp://127.0.0.1:3306 -timeout 10s
      - make test
    environment:
      - WP_TESTS_DIR=/tmp/wordpress-tests-lib-$$WP_VERSION/
      - WP_CORE_DIR=/tmp/wordpress-$$WP_VERSION/

cache:
  mount:
    - vendor

compose:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=wordpress_test
      - MYSQL_ROOT_PASSWORD=root_pass

matrix:
  WP_VERSION:
    - 4.8.4
    - 4.9.1
  PHP_VERSION:
    - 7.1
    - 7.2
