clone:
  default:
    image: plugins/git
    recursive: true
    group: clone
    submodule_update_remote: true
    submodule_override:
       docs-theme: https://github.com/PressLabs/docs-theme.git

  presslabs-org:
    image: alpine/git
    group: clone
    commands:
      # write the ssh key to disk
      - mkdir /root/.ssh
      - echo -n "$GIT_PUSH_SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      # add github to known hosts
      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      # clone presslabs-org
      - git clone -b prod git@github.com:/PressLabs/presslabs-org.git /drone/src/presslabs-org
    secrets:
      - GIT_PUSH_SSH_KEY

pipeline:
  test-gitium:
    image: presslabs/pl-test-containers:php-${PHP_VERSION}
    pull: true
    group: build
    commands:
      - bash bin/install-wp-tests.sh wordpress_test root root_pass database ${WP_VERSION} true
      - composer install --no-progress
      - dockerize --wait tcp://database:3306 -timeout 10s
      - make test
    environment:
      - WP_TESTS_DIR=/tmp/wordpress-tests-lib-${WP_VERSION}/
      - WP_CORE_DIR=/tmp/wordpress-${WP_VERSION}/

  build-docs:
    image: jobandtalent/mkdocs
    group: build
    commands:
      - cd docs/
      - pip3 install mdx_figcaption_ng
      - mkdocs build --clean
      - for i in $(ls | grep -v compiled_docs); do rm -rf $i; done
      - mkdir -p /drone/src/presslabs-org/wp-content/root/gitium/docs
      - rm -rf /drone/src/presslabs-org/wp-content/root/gitium/docs/*
      - mv compiled_docs/* /drone/src/presslabs-org/wp-content/root/gitium/docs
      - rm -rf compiled_docs/
    when:
      branch: master

  update-presslabs-org:
    image: appleboy/drone-git-push
    branch: prod
    group: docs
    commit: true
    path: /drone/src/presslabs-org
    commit_message: "[docs] Update gitium docs"
    remote: git@github.com:/Presslabs/presslabs-org.git
    secrets:
      - GIT_PUSH_SSH_KEY
    when:
      branch: master

services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=wordpress_test
      - MYSQL_ROOT_PASSWORD=root_pass

workspace:
   base: /drone
   path: src/gitium

matrix:
  WP_VERSION:
    - 4.9.7
  PHP_VERSION:
    - 7.1
    - 7.2
