language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=0
addons:
  code_climate:
    repo_token: 819c356e2d022f98e4e2717dbd459c3801fef95241a2db7261596a0482dd6ca3
before_script:
  - composer install --dev
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: ./vendor/bin/phpunit
after_success:
  - vendor/bin/test-reporter
