language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=0
before_script:
  - composer install --dev
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script: ./vendor/bin/phpunit --tap --coverage-clover build/logs/clover.xml
after_script:
  - bash bin/code-climate-coverage.sh
